CREATE TABLE "agent" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "agent_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"project_id" integer,
	"grp_id" integer,
	"role" text NOT NULL,
	"model" text NOT NULL,
	"session_id" text,
	"session_tokens" bigint DEFAULT 0 NOT NULL,
	"total_tokens" bigint DEFAULT 0 NOT NULL,
	"cwd" text,
	"activity" text,
	"state" text DEFAULT 'idle' NOT NULL,
	"created_at" bigint NOT NULL,
	"token" text,
	"stable_hash" text,
	"idle_turns" integer DEFAULT 0 NOT NULL,
	"loop_file" text,
	"loop_count" integer DEFAULT 0 NOT NULL,
	"context_window" integer,
	"runtime" text DEFAULT 'claude' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "channel" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "channel_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"project_id" integer,
	"grp_id" integer,
	"kind" text NOT NULL,
	"status" text DEFAULT 'open' NOT NULL,
	"created_at" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "cursor" (
	"agent_id" integer,
	"channel_id" integer,
	"last_seq" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "cursor_pkey" PRIMARY KEY("agent_id","channel_id")
);
--> statement-breakpoint
CREATE TABLE "escalation" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "escalation_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"grp_id" integer,
	"agent_id" integer,
	"severity" text DEFAULT 'advisory' NOT NULL,
	"question" text NOT NULL,
	"chain_state" text DEFAULT 'pm' NOT NULL,
	"answered_by" text,
	"answer" text,
	"ref_note_id" integer,
	"checkpoint_sha" text,
	"created_at" bigint NOT NULL,
	"answered_at" bigint,
	"brief" text,
	"kind" text,
	CONSTRAINT "chain_state_state" CHECK ("chain_state" IN ('pm', 'architect', 'cos', 'boss', 'answered', 'revoked'))
);
--> statement-breakpoint
CREATE TABLE "event" (
	"seq" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "event_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"channel_id" integer,
	"grp_id" integer,
	"author" text NOT NULL,
	"kind" text NOT NULL,
	"intent" text,
	"severity" text,
	"body" text DEFAULT '' NOT NULL,
	"target" text,
	"meta_json" jsonb DEFAULT '{}' NOT NULL,
	"at" bigint NOT NULL,
	"correlation_id" text,
	"trace_id" text,
	"span_id" text
);
--> statement-breakpoint
CREATE TABLE "grp" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "grp_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"project_id" integer NOT NULL,
	"name" text NOT NULL,
	"branch" text,
	"status" text DEFAULT 'DRAFT' NOT NULL,
	"owns_json" jsonb DEFAULT '[]' NOT NULL,
	"budget_tokens" bigint,
	"spent_tokens" bigint DEFAULT 0 NOT NULL,
	"created_at" bigint NOT NULL,
	"paused_at" bigint,
	"merge_seq" integer,
	"pr_number" integer,
	"pr_seen_at" bigint DEFAULT 0 NOT NULL,
	"pr_checks_sig" text,
	"rl_resets_at" bigint,
	"approved_at" bigint,
	"blocked_on" integer,
	"merge_seq_at" bigint,
	"pr_retries" integer DEFAULT 0 NOT NULL,
	"shared_grant" text,
	"rebase_seen" text,
	"rebase_seen_at" bigint,
	"sandbox_id" text,
	"sandbox_at" bigint,
	"pr_title" text,
	"pr_summary" text,
	"pause_reason" text,
	"paused_from" text,
	CONSTRAINT "grp_project_id_name_unique" UNIQUE("project_id","name"),
	CONSTRAINT "status_state" CHECK ("status" IN ('PLANNING', 'DRAFT', 'RUNNING', 'PAUSING', 'PAUSED', 'PARKED', 'PR_OPEN', 'DISSOLVED'))
);
--> statement-breakpoint
CREATE TABLE "idempotency_request" (
	"caller" text,
	"route" text,
	"key" text,
	"payload_hash" text NOT NULL,
	"state" text NOT NULL,
	"status" integer,
	"body" text,
	"content_type" text,
	"created_at" bigint NOT NULL,
	"updated_at" bigint NOT NULL,
	CONSTRAINT "idempotency_request_pkey" PRIMARY KEY("caller","route","key")
);
--> statement-breakpoint
CREATE TABLE "job" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "job_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"kind" text NOT NULL,
	"grp_id" integer,
	"agent_id" integer,
	"slice_id" integer,
	"payload_json" jsonb DEFAULT '{}' NOT NULL,
	"priority" integer DEFAULT 0 NOT NULL,
	"state" text DEFAULT 'pending' NOT NULL,
	"pid" integer,
	"error" text,
	"enqueued_at" bigint NOT NULL,
	"started_at" bigint,
	"ended_at" bigint,
	"checkpoint_sha" text,
	"correlation_id" text,
	"trace_id" text,
	"parent_span_id" text,
	"trace_flags" integer,
	CONSTRAINT "state_state" CHECK ("state" IN ('pending', 'running', 'done', 'failed', 'cancelled'))
);
--> statement-breakpoint
CREATE TABLE "lease" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "lease_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"resource" text NOT NULL,
	"grp_id" integer,
	"agent_id" integer,
	"args_json" jsonb DEFAULT '{}' NOT NULL,
	"resolved_cmd" text,
	"state" text DEFAULT 'queued' NOT NULL,
	"exit_code" integer,
	"log_path" text,
	"result_digest" text,
	"enqueued_at" bigint NOT NULL,
	"started_at" bigint,
	"ended_at" bigint,
	"head_sha" text,
	CONSTRAINT "state_state" CHECK ("state" IN ('queued', 'running', 'done', 'failed'))
);
--> statement-breakpoint
CREATE TABLE "member" (
	"channel_id" integer,
	"agent_id" integer,
	"mode" text DEFAULT 'full' NOT NULL,
	CONSTRAINT "member_pkey" PRIMARY KEY("channel_id","agent_id")
);
--> statement-breakpoint
CREATE TABLE "note" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "note_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"project_id" integer,
	"grp_id" integer,
	"slice_id" integer,
	"task_id" integer,
	"kind" text NOT NULL,
	"lang" text DEFAULT 'zh' NOT NULL,
	"body" text NOT NULL,
	"frontmatter_json" jsonb DEFAULT '{}' NOT NULL,
	"export_path" text,
	"at" bigint NOT NULL,
	"supersedes" integer
);
--> statement-breakpoint
CREATE TABLE "project" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "project_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL UNIQUE,
	"repo_path" text NOT NULL,
	"remote" text,
	"config_json" jsonb DEFAULT '{}' NOT NULL,
	"created_at" bigint NOT NULL,
	"sandbox_id" text,
	"sandbox_at" bigint,
	"base_branch" text,
	"base_branch_pinned" boolean DEFAULT false NOT NULL
);
--> statement-breakpoint
CREATE TABLE "resource" (
	"name" text PRIMARY KEY,
	"concurrency" integer DEFAULT 1 NOT NULL,
	"template" text NOT NULL,
	"arg_schema_json" jsonb DEFAULT '{}' NOT NULL,
	"error_regex" text,
	"cwd" text,
	"tags_json" jsonb DEFAULT '[]' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "runtime_auth" (
	"runtime" text PRIMARY KEY,
	"mode" text NOT NULL,
	"secret" text NOT NULL,
	"base_url" text,
	"updated_at" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "setting" (
	"k" text PRIMARY KEY,
	"v" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "slice" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "slice_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"grp_id" integer NOT NULL,
	"seq" integer NOT NULL,
	"title" text NOT NULL,
	"accept_spec" text NOT NULL,
	"difficulty" text DEFAULT 'normal' NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"gates_json" jsonb DEFAULT '{}' NOT NULL,
	"budget_tokens" bigint,
	"spent_tokens" bigint DEFAULT 0 NOT NULL,
	"depends_on" integer,
	"created_at" bigint NOT NULL,
	"base_sha" text,
	"retries" integer DEFAULT 0 NOT NULL,
	"awaiting_at" bigint,
	CONSTRAINT "slice_grp_id_seq_unique" UNIQUE("grp_id","seq"),
	CONSTRAINT "status_state" CHECK ("status" IN ('pending', 'running', 'gate', 'qa', 'awaiting_boss', 'accepted', 'rejected'))
);
--> statement-breakpoint
CREATE TABLE "span" (
	"trace_id" text,
	"span_id" text,
	"parent_span_id" text,
	"name" text NOT NULL,
	"kind" text NOT NULL,
	"started_at" bigint NOT NULL,
	"duration_ms" double precision NOT NULL,
	"status" text NOT NULL,
	"attributes_json" jsonb DEFAULT '{}' NOT NULL,
	"project_id" integer,
	"grp_id" integer,
	"slice_id" integer,
	"status_message" text,
	CONSTRAINT "span_pkey" PRIMARY KEY("trace_id","span_id")
);
--> statement-breakpoint
CREATE TABLE "task" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "task_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"grp_id" integer NOT NULL,
	"slice_id" integer,
	"title" text NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"owner_agent_id" integer,
	"depends_on_json" jsonb DEFAULT '[]' NOT NULL,
	"claim_json" jsonb,
	"created_at" bigint NOT NULL,
	CONSTRAINT "status_state" CHECK ("status" IN ('pending', 'in_progress', 'done'))
);
--> statement-breakpoint
CREATE TABLE "usage_snapshot" (
	"runtime" text PRIMARY KEY,
	"json" jsonb NOT NULL,
	"at" bigint NOT NULL,
	"hold_until" bigint
);
--> statement-breakpoint
CREATE UNIQUE INDEX "agent_token" ON "agent" ("token") WHERE "token" IS NOT NULL;--> statement-breakpoint
CREATE INDEX "escalation_open" ON "escalation" ("chain_state","created_at");--> statement-breakpoint
CREATE INDEX "event_channel" ON "event" ("channel_id","seq");--> statement-breakpoint
CREATE INDEX "event_grp" ON "event" ("grp_id","seq");--> statement-breakpoint
CREATE INDEX "event_correlation" ON "event" ("correlation_id","seq");--> statement-breakpoint
CREATE INDEX "idempotency_request_age" ON "idempotency_request" ("updated_at");--> statement-breakpoint
CREATE INDEX "job_dispatch" ON "job" ("state","priority" DESC,"id");--> statement-breakpoint
CREATE INDEX "job_grp" ON "job" ("grp_id","state");--> statement-breakpoint
CREATE INDEX "job_correlation" ON "job" ("correlation_id");--> statement-breakpoint
CREATE INDEX "lease_queue" ON "lease" ("resource","state","id");--> statement-breakpoint
CREATE INDEX "note_lookup" ON "note" ("project_id","kind","at" DESC);--> statement-breakpoint
CREATE INDEX "span_age" ON "span" ("started_at");--> statement-breakpoint
CREATE INDEX "span_scope" ON "span" ("grp_id","slice_id","started_at");--> statement-breakpoint
CREATE INDEX "task_grp" ON "task" ("grp_id","status");--> statement-breakpoint
ALTER TABLE "agent" ADD CONSTRAINT "agent_project_id_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "project"("id");--> statement-breakpoint
ALTER TABLE "agent" ADD CONSTRAINT "agent_grp_id_grp_id_fkey" FOREIGN KEY ("grp_id") REFERENCES "grp"("id");--> statement-breakpoint
ALTER TABLE "channel" ADD CONSTRAINT "channel_project_id_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "project"("id");--> statement-breakpoint
ALTER TABLE "channel" ADD CONSTRAINT "channel_grp_id_grp_id_fkey" FOREIGN KEY ("grp_id") REFERENCES "grp"("id");--> statement-breakpoint
ALTER TABLE "cursor" ADD CONSTRAINT "cursor_agent_id_agent_id_fkey" FOREIGN KEY ("agent_id") REFERENCES "agent"("id");--> statement-breakpoint
ALTER TABLE "cursor" ADD CONSTRAINT "cursor_channel_id_channel_id_fkey" FOREIGN KEY ("channel_id") REFERENCES "channel"("id");--> statement-breakpoint
ALTER TABLE "escalation" ADD CONSTRAINT "escalation_grp_id_grp_id_fkey" FOREIGN KEY ("grp_id") REFERENCES "grp"("id");--> statement-breakpoint
ALTER TABLE "escalation" ADD CONSTRAINT "escalation_agent_id_agent_id_fkey" FOREIGN KEY ("agent_id") REFERENCES "agent"("id");--> statement-breakpoint
ALTER TABLE "escalation" ADD CONSTRAINT "escalation_ref_note_id_note_id_fkey" FOREIGN KEY ("ref_note_id") REFERENCES "note"("id");--> statement-breakpoint
ALTER TABLE "event" ADD CONSTRAINT "event_channel_id_channel_id_fkey" FOREIGN KEY ("channel_id") REFERENCES "channel"("id");--> statement-breakpoint
ALTER TABLE "event" ADD CONSTRAINT "event_grp_id_grp_id_fkey" FOREIGN KEY ("grp_id") REFERENCES "grp"("id");--> statement-breakpoint
ALTER TABLE "grp" ADD CONSTRAINT "grp_project_id_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "project"("id");--> statement-breakpoint
ALTER TABLE "grp" ADD CONSTRAINT "grp_blocked_on_grp_id_fkey" FOREIGN KEY ("blocked_on") REFERENCES "grp"("id");--> statement-breakpoint
ALTER TABLE "job" ADD CONSTRAINT "job_grp_id_grp_id_fkey" FOREIGN KEY ("grp_id") REFERENCES "grp"("id");--> statement-breakpoint
ALTER TABLE "job" ADD CONSTRAINT "job_agent_id_agent_id_fkey" FOREIGN KEY ("agent_id") REFERENCES "agent"("id");--> statement-breakpoint
ALTER TABLE "job" ADD CONSTRAINT "job_slice_id_slice_id_fkey" FOREIGN KEY ("slice_id") REFERENCES "slice"("id");--> statement-breakpoint
ALTER TABLE "lease" ADD CONSTRAINT "lease_resource_resource_name_fkey" FOREIGN KEY ("resource") REFERENCES "resource"("name");--> statement-breakpoint
ALTER TABLE "lease" ADD CONSTRAINT "lease_grp_id_grp_id_fkey" FOREIGN KEY ("grp_id") REFERENCES "grp"("id");--> statement-breakpoint
ALTER TABLE "lease" ADD CONSTRAINT "lease_agent_id_agent_id_fkey" FOREIGN KEY ("agent_id") REFERENCES "agent"("id");--> statement-breakpoint
ALTER TABLE "member" ADD CONSTRAINT "member_channel_id_channel_id_fkey" FOREIGN KEY ("channel_id") REFERENCES "channel"("id");--> statement-breakpoint
ALTER TABLE "member" ADD CONSTRAINT "member_agent_id_agent_id_fkey" FOREIGN KEY ("agent_id") REFERENCES "agent"("id");--> statement-breakpoint
ALTER TABLE "note" ADD CONSTRAINT "note_project_id_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "project"("id");--> statement-breakpoint
ALTER TABLE "note" ADD CONSTRAINT "note_grp_id_grp_id_fkey" FOREIGN KEY ("grp_id") REFERENCES "grp"("id");--> statement-breakpoint
ALTER TABLE "note" ADD CONSTRAINT "note_slice_id_slice_id_fkey" FOREIGN KEY ("slice_id") REFERENCES "slice"("id");--> statement-breakpoint
ALTER TABLE "note" ADD CONSTRAINT "note_task_id_task_id_fkey" FOREIGN KEY ("task_id") REFERENCES "task"("id");--> statement-breakpoint
ALTER TABLE "note" ADD CONSTRAINT "note_supersedes_note_id_fkey" FOREIGN KEY ("supersedes") REFERENCES "note"("id");--> statement-breakpoint
ALTER TABLE "slice" ADD CONSTRAINT "slice_grp_id_grp_id_fkey" FOREIGN KEY ("grp_id") REFERENCES "grp"("id");--> statement-breakpoint
ALTER TABLE "slice" ADD CONSTRAINT "slice_depends_on_slice_id_fkey" FOREIGN KEY ("depends_on") REFERENCES "slice"("id");--> statement-breakpoint
ALTER TABLE "task" ADD CONSTRAINT "task_grp_id_grp_id_fkey" FOREIGN KEY ("grp_id") REFERENCES "grp"("id");--> statement-breakpoint
ALTER TABLE "task" ADD CONSTRAINT "task_slice_id_slice_id_fkey" FOREIGN KEY ("slice_id") REFERENCES "slice"("id");--> statement-breakpoint
ALTER TABLE "task" ADD CONSTRAINT "task_owner_agent_id_agent_id_fkey" FOREIGN KEY ("owner_agent_id") REFERENCES "agent"("id");