import { z } from "zod";
import { SAY_KEYS, ZH_SAY } from "../src/platform/text/lang.ts";

/**
 * How much of what the orchestrator says has been translated, written into both
 * READMEs between markers.
 *
 * Two surfaces, because they are two mechanisms and only one of them is ever
 * going to reach 100%: the panel's catalogs are generated by `lingui extract`
 * and a missing string there is a gap, while `lang.ts` is partial on purpose —
 * an untranslated key falls back to the English row, which is a sentence in the
 * other language rather than a build failure.
 */

const MARK = { open: "<!-- i18n:table -->", close: "<!-- /i18n:table -->" };

/** English is the source language for both surfaces, so it has no column: one
 *  that can only ever say 100% teaches the reader to stop looking. A third
 *  language is a third column, which is why the shape is surfaces × locales. */
const DOCS = {
  "README.md": {
    head: ["Surface", "Strings", "中文"],
    rows: ["Panel (`web/src`)", "Orchestrator messages (`src/platform/text/lang.ts`)"],
  },
  "README.zh-CN.md": {
    head: ["界面", "字符串", "中文"],
    rows: ["面板（`web/src`）", "编排器消息（`src/platform/text/lang.ts`）"],
  },
};

type Row = { total: number; done: number };

const pct = (r: Row): string => `${r.done} (${r.total === 0 ? 100 : Math.round((r.done / r.total) * 100)}%)`;

/** Only the field this counts. `lingui extract` writes four more per message and
 *  is free to write a fifth; a schema that refused one would make a new Lingui
 *  release look like a broken README. */
const CatalogSchema = z.record(z.string(), z.object({ translation: z.string().optional() }));

async function panel(): Promise<Row> {
  const entries = Object.values(CatalogSchema.parse(await Bun.file("web/src/locales/zh.json").json()));
  return { total: entries.length, done: entries.filter((m) => (m.translation ?? "").trim() !== "").length };
}

/** `SAY_KEYS` is the registry — `EN` is what declares a key exists — and `ZH_SAY`
 *  is partial on purpose, so this is a real fraction rather than a formality. */
const orchestrator = (): Row => ({ total: SAY_KEYS.length, done: SAY_KEYS.filter((k) => ZH_SAY[k]).length });

const table = (doc: (typeof DOCS)[keyof typeof DOCS], rows: Row[]): string =>
  [
    MARK.open,
    `| ${doc.head.join(" | ")} |`,
    "| --- | ---: | ---: |",
    ...rows.map((r, i) => `| ${doc.rows[i]} | ${r.total} | ${pct(r)} |`),
    MARK.close,
  ].join("\n");

/** Replaces what is between the markers, so the prose around them is nobody's
 *  business but the person who wrote it. */
function splice(doc: string, block: string): string {
  const from = doc.indexOf(MARK.open);
  const to = doc.indexOf(MARK.close);
  if (from === -1 || to === -1) throw new Error(`no ${MARK.open} … ${MARK.close} block to write into`);
  return doc.slice(0, from) + block + doc.slice(to + MARK.close.length);
}

const check = process.argv.includes("--check");
const rows: Row[] = [await panel(), orchestrator()];
let stale = false;

for (const [file, doc] of Object.entries(DOCS)) {
  const current = await Bun.file(file).text();
  const next = splice(current, table(doc, rows));
  if (next === current) continue;
  if (check) {
    console.error(`${file}: translation table is stale — run \`bun run i18n:progress\``);
    stale = true;
    continue;
  }
  await Bun.write(file, next);
  console.log(`${file}: updated`);
}

if (stale) process.exit(1);
if (!check) for (const [i, r] of rows.entries()) console.log(`${DOCS["README.md"].rows[i]}  ${pct(r)} of ${r.total}`);
