import { z } from "zod";
import { endonymOf, LOCALES } from "../src/contracts/config.ts";
import { SAY_KEYS, ZH_SAY } from "../src/platform/text/lang.ts";

/**
 * How much of what the orchestrator says has been translated, one bar per
 * language, written into both READMEs between markers.
 *
 * The bars are `progress-bar.xyz`, which renders a percentage as an SVG. It was
 * `inlang.com/badge` first — the service every "translation status" answer
 * points at — and that returns 404 for every repository now, including the ones
 * whose READMEs still link it. Checked before it was written down here, which is
 * the only reason this is not a third broken image.
 */
/**
 * Two surfaces, because they are two mechanisms and only one can reach 100%:
 * the panel's catalogs are generated by `lingui extract`, while `lang.ts` is
 * partial on purpose — an untranslated key there falls back to the English row,
 * which is a sentence in the other language rather than a build failure. Only
 * the panel is per-language; `lang.ts` speaks Chinese and English only.
 */

const MARK = { open: "<!-- i18n:table -->", close: "<!-- /i18n:table -->" };
const BAR = (percent: number) => `https://progress-bar.xyz/${percent}?width=140&suffix=%25`;

/** Only the field this counts. `lingui extract` writes four more per message and
 *  is free to write a fifth; a schema that refused one would make a new Lingui
 *  release look like a broken README. */
const CatalogSchema = z.record(z.string(), z.object({ translation: z.string().optional() }));

type Row = { label: string; done: number; total: number; source?: boolean };

const pct = (r: Row): number => (r.total === 0 ? 100 : Math.round((r.done / r.total) * 100));

async function panelRows(): Promise<Row[]> {
  const rows: Row[] = [];
  for (const locale of LOCALES) {
    const entries = Object.values(CatalogSchema.parse(await Bun.file(`web/src/locales/${locale}.json`).json()));
    // The source language needs no translations: every message falls back to the
    // English the macro hashed, so it is complete by construction rather than by
    // anybody's work.
    const done = locale === "en" ? entries.length : entries.filter((m) => (m.translation ?? "").trim() !== "").length;
    rows.push({ label: endonymOf(locale), done, total: entries.length, ...(locale === "en" ? { source: true } : {}) });
  }
  return rows;
}

const orchestratorRow = (): Row => ({
  label: endonymOf("zh"),
  done: SAY_KEYS.filter((k) => ZH_SAY[k]).length,
  total: SAY_KEYS.length,
});

/** One entry per README, so the renderer below has no branches in it: the two
 *  documents differ only in their words. */
const COPY = {
  "README.md": {
    head: ["Language", "Progress", "Messages"],
    source: "source",
    panel: (n: number) => `**Panel** · ${n} messages`,
    orchestrator: (n: number) => `**What the orchestrator says** · ${n}, Chinese and English only`,
    note: "`bun run i18n:progress` regenerates this; CI fails if it is stale. English is the source, so it needs none.",
  },
  "README.zh-CN.md": {
    head: ["语言", "进度", "条数"],
    source: "源语言",
    panel: (n: number) => `**面板** · ${n} 条消息`,
    orchestrator: (n: number) => `**编排器自己说的话** · ${n} 条，只有中英两套`,
    note: "`bun run i18n:progress` 重新生成；过期时 CI 会红。英文是源语言，不需要翻译。",
  },
} as const;

type Copy = (typeof COPY)[keyof typeof COPY];

const line = (r: Row, copy: Copy): string =>
  `| ${r.label} | ![](${BAR(pct(r))}) | ${r.source ? copy.source : `${r.done} / ${r.total}`} |`;

const table = (rows: Row[], copy: Copy): string[] => [
  `| ${copy.head.join(" | ")} |`,
  "| --- | --- | ---: |",
  ...rows.map((r) => line(r, copy)),
  "",
];

const block = (rows: Row[], orchestrator: Row, copy: Copy): string =>
  [
    MARK.open,
    copy.panel(rows[0]?.total ?? 0),
    "",
    ...table(rows, copy),
    copy.orchestrator(orchestrator.total),
    "",
    ...table([orchestrator], copy),
    copy.note,
    MARK.close,
  ].join("\n");

function splice(doc: string, next: string): string {
  const from = doc.indexOf(MARK.open);
  const to = doc.indexOf(MARK.close);
  if (from === -1 || to === -1) throw new Error(`no ${MARK.open} … ${MARK.close} block to write into`);
  return doc.slice(0, from) + next + doc.slice(to + MARK.close.length);
}

const check = process.argv.includes("--check");
const panel = await panelRows();
const orchestrator = orchestratorRow();
let stale = false;

for (const [doc, copy] of Object.entries(COPY)) {
  const current = await Bun.file(doc).text();
  const next = splice(current, block(panel, orchestrator, copy));
  if (next === current) continue;
  if (check) {
    console.error(`${doc}: translation progress is stale — run \`bun run i18n:progress\``);
    stale = true;
    continue;
  }
  await Bun.write(doc, next);
  console.log(`${doc}: updated`);
}

if (stale) process.exit(1);
if (!check)
  for (const r of [...panel, orchestrator])
    console.log(`${r.label.padEnd(10)} ${String(pct(r)).padStart(3)}%  ${r.done}/${r.total}`);
