import { LOCALES } from "../src/contracts/config.ts";
import { translations } from "./lingui-catalogs.ts";
import { writeOrCheck } from "./generated-file.ts";

/**
 * The messages the **server** renders, as a plain module it can import.
 *
 * ADR 041 kept Lingui out of the server because `release.yml` builds with
 * `bun build --compile`, which takes no plugin — so a `.po` cannot be compiled
 * on the way in. That blocks importing a catalog; it never blocked running the
 * library. This script is the way round it: the `.po` files are read at build
 * time and their ICU sources written out as TypeScript.
 */
/**
 * A dot, not a prefix list.
 *
 * Lingui hashes an id from the English unless one is written down, and those
 * hashes are short and dotless — so "has an explicit id" is exactly "somebody
 * meant the server to name this by hand", which is the question this filter is
 * asking. A prefix whitelist answers a different one and goes stale: written as
 * `ev.` it silently dropped the 52 `check.` messages that already existed.
 */
const named = (id: string): boolean => id.includes(".");
const TARGET = "src/platform/text/messages.generated.ts";

const HEAD = `// Generated by \`bun run i18n:messages\` from web/src/locales/*.po. Do not edit.
//
// Every message with an explicit id — the ones somebody meant the server to name
// by hand, as opposed to the ones Lingui hashed out of their English. They are
// written in \`web/src/shared/messages.ts\` and \`web/src/features/settings/checks.ts\`,
// which is also where a comment about one belongs.
//
// \`MessageId\` is a literal union, so a server naming an id this table does not
// have fails \`tsc\` — that is the whole guard, and it is why there is no parity
// test beside it.
import type { Locale } from "../../contracts/config.ts";
`;

export async function generate(): Promise<string> {
  const en = await translations("en");
  const ids = Object.keys(en.messages).filter(named).sort();
  const rows: string[] = [];
  for (const locale of LOCALES) {
    const { messages } = await translations(locale);
    // English is the fallback for a locale that is somehow short a message, so
    // the generated table is total and the server never renders a bare id.
    const body = ids.map((id) => `    ${JSON.stringify(id)}: ${JSON.stringify(messages[id] || en.messages[id])},`);
    rows.push(`  ${JSON.stringify(locale)}: {\n${body.join("\n")}\n  },`);
  }
  return (
    `${HEAD}\nexport const MESSAGE_IDS = [\n${ids.map((id) => `  ${JSON.stringify(id)},`).join("\n")}\n] as const;\n\n` +
    `export type MessageId = (typeof MESSAGE_IDS)[number];\n\n` +
    `export const MESSAGES: Record<Locale, Record<MessageId, string>> = {\n${rows.join("\n")}\n};\n`
  );
}

if (import.meta.main) await writeOrCheck(TARGET, await generate(), "web/src/locales/*.po", "i18n:messages");
