import { expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { CJK } from "../support/ast.ts";

/**
 * The two files a person opens before the panel exists.
 *
 * `server-speaks-one-language` parses `src/**` and `panel-speaks-english`
 * parses `web/src/**`, so both walk a babel AST — which is why nine lines of
 * Chinese sat in `config/default.yaml` through the whole branch whose thesis is
 * that this product does not assume its reader. That is the file the boss edits
 * by hand, and ADR 043's motivating sentence is a German boss who installed this
 * and got a German panel and Chinese webhooks.
 */
/**
 * Zero tolerance rather than a ratchet, because both files are at zero: there is
 * nothing to walk down and a baseline would only be somewhere to hide the next
 * one. `roles/*.yaml` is deliberately out — `dispatcher.yaml`'s worked example is
 * `greet("x","zh") returns 你好 x`, where `你好` is the function's return value.
 */

/**
 * What the English README may still hold, and only this.
 *
 * The language table between the markers is generated by
 * `scripts/i18n-progress.ts` and its first column is CLDR's endonyms — `简体中文`
 * is the correct content of a row naming Simplified Chinese. The switcher at the
 * top names the other README the same way.
 */
const GENERATED = /<!-- i18n:table -->[\s\S]*?<!-- \/i18n:table -->/g;
const SWITCHER = /^\[English\].*$/m;

const cjkLines = (text: string): string[] =>
  text
    .split("\n")
    .map((line, i) => [i + 1, line] as const)
    .filter(([, line]) => CJK.test(line))
    .map(([n, line]) => `${n}: ${line.trim()}`);

test("config/default.yaml is readable by a boss who does not read Chinese", () => {
  expect(cjkLines(readFileSync("config/default.yaml", "utf8"))).toEqual([]);
});

test("the English README names panes the way the panel spells them", () => {
  const readme = readFileSync("README.md", "utf8").replace(GENERATED, "").replace(SWITCHER, "");
  expect(cjkLines(readme)).toEqual([]);
});

/**
 * The file a contributor opens before writing an ADR, which the commit that
 * translated `config/default.yaml` walked past — it was named by hand there, and
 * a guard that lists two files finds two files.
 */
test("the ADR index is in the language the ADRs are written in", () => {
  expect(cjkLines(readFileSync("docs/adr/README.md", "utf8"))).toEqual([]);
});
